site_name: OAH
nav:
  - Home: index.md
  - How-To: howto.md
  - Documentation:
      - Applications:
        - BerkeleyGW Module Example: Documentation/Applications/berkeleygw_module.md
        - BerkeleyGW Build Example: Documentation/Applications/berkeleygw_build.md
        - Application Module Template: Documentation/Applications/applications_template_module.md
        - Application Build Template: Documentation/Applications/applications_template_build.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.path
    - toc.follow
  icon:
    admonition:
      example: material/arrow-top-left-bottom-right

markdown_extensions:
  - attr_list
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - admonition
