site_name: My Docs
site_url: https://oahull0112.github.io
nav:
    - Home: index.md
    - Article: article.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.follow
