site_name: OAH
nav:
  - Home: index.md
  - How-To: howto.md
  - Documentation:
      - Applications:
        - VASP: Documentation/Applications/vasp.md
        - Combined Module/Build Template: Documentation/Applications/applications_template.md
        - BerkeleyGW Combined Module/Build Example: Documentation/Applications/berkeleygw_example.md
        - BerkeleyGW Module Example: Documentation/Applications/berkeleygw_module.md
        - BerkeleyGW Build Example: Documentation/Applications/berkeleygw_build.md
        - Application Module Template: Documentation/Applications/applications_template_module.md
        - Application Build Template: Documentation/Applications/applications_template_build.md
      - Programming Languages:
        - Fortran Example: Documentation/ProgrammingLanguages/fortran.md
      - Libraries:
        - Libraries Overview: Documentation/Libraries/intro_libraries.md
        - Libraries Deepdive: Documentation/Libraries/deepdive.md
        - MKL: Documentation/Libraries/mkl.md
        - LibSci: Documentation/Libraries/libsci.md
        - FFTW: Documentation/Libraries/fftw.md
        - LAPACK: Documentation/Libraries/lapack.md
      - Debugging:
        - GDB: Documentation/Debugging/gdb.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.path
    - toc.follow
  icon:
    admonition:
      example: material/arrow-top-left-bottom-right

markdown_extensions:
  - toc:
      permalink: "#"
  - attr_list
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - admonition
