site_name: OAH
nav:
  - Home: index.md
  - How-To: howto.md
  - Documentation:
      - Applications:
        - Applications: Documentation/Applications/applications.md
        - BerkeleyGW:
          - Documentation/Applications/berkeleygw.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.path
    - toc.follow

markdown_extensions:
  - attr_list
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
