site_name: My Docs
nav:
    - Home: index.md
    - Set up: howto.md
      #    - Applications: 
      #      - Applications/applications.md
      #      - BerkeleyGW: Applications/BerkeleyGW/berkeleygw.md 
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
